# Generated by Django 4.0.3 on 2022-03-18 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DexUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_image_url', models.ImageField(null=True, upload_to='actionimages')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.item')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pokemon_kind', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('standard_height', models.CharField(max_length=10)),
                ('standard_alpha_height', models.CharField(max_length=10)),
                ('standard_weight', models.FloatField()),
                ('standard_alpha_weight', models.FloatField()),
                ('is_shiny', models.BooleanField(default=False)),
                ('is_alpha', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poketype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TypePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.pokemon')),
                ('poketype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.poketype')),
            ],
        ),
        migrations.CreateModel(
            name='RegionPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.pokemon')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.region')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('image_url', models.ImageField(null=True, upload_to='')),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.dexuser')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='home_regions',
            field=models.ManyToManyField(through='shinydexapi.RegionPokemon', to='shinydexapi.region'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poke_items',
            field=models.ManyToManyField(through='shinydexapi.ItemPokemon', to='shinydexapi.item'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poke_types',
            field=models.ManyToManyField(through='shinydexapi.TypePokemon', to='shinydexapi.poketype'),
        ),
        migrations.AddField(
            model_name='itempokemon',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.pokemon'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.dexuser')),
            ],
        ),
        migrations.CreateModel(
            name='Caught',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isShiny', models.BooleanField(default=True)),
                ('isAlpha', models.BooleanField(default=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinydexapi.dexuser')),
            ],
        ),
    ]
