# Generated by Django 4.0.3 on 2022-03-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinydexapi', '0002_pokemon_home_regions_pokemon_poke_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='isAlpha',
            new_name='is_alpha',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='isShiny',
            new_name='is_shiny',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemonKind',
            new_name='pokemon_kind',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='standardAlphaHeight',
            new_name='standard_alpha_height',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='standardAlphaWeight',
            new_name='standard_alpha_weight',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='standardHeight',
            new_name='standard_height',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='standardWeight',
            new_name='standard_weight',
        ),
    ]
