# Generated by Django 4.0.3 on 2022-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinydexapi', '0005_rename_isalpha_caught_is_alpha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='poke_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
