# Generated by Django 4.0.3 on 2022-03-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinydexapi', '0006_pokemon_poke_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='poke_image',
        ),
    ]
