# Generated by Django 4.0.3 on 2022-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinydexapi', '0007_remove_pokemon_poke_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
